### ISSUE TITLE
Support for rendering single frames of optimized gifs

### ISSUE THREAD

**Issue by Prinzhorn** [qdot/giflib.js#1]
Currently `copyImageToCanvas` seems to simply use the data of the current frame. But due to optimization, here's what I get for many gifs when rendering every frame

![screenshot from 2014-07-26 19 45 09](https://cloud.githubusercontent.com/assets/679144/3711811/a9b6bec2-14ec-11e4-8e7b-87b806fcee66.png)

Using this simple code

``` js
var gifFile = new GifLibFile(file);

gifFile.load().then(function(gif) {
    var imageIndex;

    for(imageIndex = 0; imageIndex < gif.imageCount; imageIndex++) {
        var canvas = document.createElement('canvas');
        gifFile.copyImageToCanvas(gif, imageIndex, canvas);
        document.body.appendChild(canvas);
    }

    gifFile.close();
}, function() {
    alert('Could not load gif file.)');
});
```

The Bender gif for reference: https://cloud.githubusercontent.com/assets/679144/3711815/ee6faea2-14ec-11e4-975c-793d0c2ed860.gif

In ImageMagick the option to fix this is [-coalesce](http://www.imagemagick.org/script/command-line-options.php?#coalesce). I don't know enough about giflib to decide if it's easy to fix. It's needed though in order to make use of the library.

**Comment by qdot** [comment]
Well damn. I apparently never commited the optimized decomp work that I did. Just committed and pushed. Pull and see if that fixes your problem (though be warned, subsection decomp is still funky)

**Comment by Prinzhorn** [comment]
Awesome. The bender gif is fixed. But I have other gifs which still have issues.

![q8sdqcw](https://cloud.githubusercontent.com/assets/679144/3711909/1da8ef26-14f2-11e4-92f3-ca99d50b7e73.gif)
![screenshot from 2014-07-26 20 24 35](https://cloud.githubusercontent.com/assets/679144/3711910/225e58da-14f2-11e4-9e45-786718264c50.png)

**Comment by qdot** [comment]
Yeah, that would be the subsection copying funkiness that I was mentioning. Will close this out and file something new for that.

**Comment by Prinzhorn** [comment]
Thanks
