### ISSUE TITLE
Problem with memory

### ISSUE THREAD

**Issue by Onefabis** [qdot/giflib.js#9]
Something strange with memory, looks like code doesn't clear memory for the next gif completely. Laest 'copyImageToCanvas ' use 'decompBuffer', but it ignore dispose method and through thansparensy areas pixels from previous frame appear. But sometimes gispose methods may differ. Also, in some Gifs the first frame has some bugs as well, even there is no previous frame. The previous method copyImageToCanvasPure works a little bit better, some gifs work ok, but only once. I think the reason is in Module._free() usage. It should clear the memory somewhere.

**Comment by qdot** [comment]
Oh, uh, wow, had no idea people even use this. I suspect it'd be much better as a wasm module now.

**Comment by Onefabis** [comment]
> Oh, uh, wow, had no idea people even use this. I suspect it'd be much better as a wasm module now.

Actually, because your solution much simpler, without requirements to install another wasm/wuff/node.js libraries. And with this simplicity it still pretty much fast. Anyway, I've solve taht problem with 36 commit from yout github. No every frame rendered pretty much ok in most cases.

**Comment by qdot** [comment]
Well, glad it could be of help! I'd actually completely forgotten I'd written it in the first place. :)
